### PR TITLE
Added new city config for NYC

### PR DESCRIPTION
**Pull request by spbail**
Ran pipeline and tested flask app, but doesn't show modes yet in the dropdown menu. Any thoughts why?

### CODE REVIEW

**Comment by bpben** [comment]
Sorry for the delay here: Do you mean in the showcase at insightlane.org? I believe we need to update that ourselves to make it show in there.  @j-t-t  @terryf82 

If it's not showing locally, I can try and see why.  It might need some kind of additional config.

**Comment by terryf82** [comment]
YAML configs (like the one in this P.R) are relevant to running the pipeline and generating output files (predictions & crashes).

Once those have been generated, the process for now is for me to upload them to Google Cloud, create an entry in the JS config and then re-deploy the showcase. @spbail - are the output files available somewhere I can download? (we usually use data.world for sharing but I can grab them from anywhere you like).

**Comment by spbail** [comment]
@bpben @terryf82 Apologies for the delay. I had to abandon my dev setup on my old laptop, but I will attempt to get this running again next week and will share the output. My question about the dropdown was that the output didn't show up in my local version, so yes, I'm thinking there should be a config I couldn't find to make things show up locally?

**Comment by j-t-t** [comment]
I would expect the dropdown should work. It's not immediately obvious to me what would be wrong. Can you point me to the crash dataset you're using and I can try to run it using your config on my machine?

**Comment by bpben** [comment]
@spbail Are you still interested on working to onboard NYC? If not, no worries, do you mind providing us the crash dataset you're working on and we can see if we can finish the onboarding process.  By the way, we've move to a new slack if you want to join us there: https://join.slack.com/t/insightlane/shared_invite/zt-ewlvaic7-ymYlps33v2M2~RhC4DFRGg

**Comment by spbail** [comment]
Hi all, apologies for abandoning this. Some notes:
- I downloaded the collision data from https://data.cityofnewyork.us/Public-Safety/Motor-Vehicle-Collisions-Crashes/
- I uploaded a small notebook with some exploration of the data here: https://drive.google.com/file/d/1rBVBs-TMAIrxAwSlz6OBeeljqtp0GXvv/view?usp=sharing
- 
 I also pinged you in the new Slack, happy to pair with someone to get this set up.

**Comment by j-t-t** [comment]
Dropdown seems fine, so merged

**Pull request merged**
